title: MI @ Biolab
author: Panoramedia
email: panoramedia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Machine Intelligence @ Biolab - Unibo

twitter_username: macrod68
github_username:  macrod68

sass:
    style: compressed
