title: MI@BioLab
author: Gabriele Graffieti
email: gabriele.graffieti@unibo.it
description: > # this means to ignore newlines until "baseurl:"
  Machine Intelligence @ Biolab - Unibo

twitter_username: ggraffieti
github_username:  ggraffieti

exclude: [example_posts,old_example_pages]

sass:
    style: compressed
